services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: park_access_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: park_access
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - park_postgis_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: park_access_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: chris@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5051:80"
    depends_on:
      - postgis

volumes:
  park_postgis_data: