name: postgis-park-access 
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - sqlalchemy
  - psycopg
  - streamlit
  - shapely
  - pyogrio
  - fiona
  - matplotlib
  - ipykernel
  - osmnx
  - pip
  - pip:
      - folium
      - streamlit-folium
      - python-dotenv